export const REQUEST_GET_ALL_MOVIES = 'REQUEST_GET_ALL_MOVIES';
export const REQUEST_GET_MOVIE_WITH_ID = 'REQUEST_GET_MOVIE_WITH_ID';
export const REQUEST_GET_SEARCH_MOVIES = 'REQUEST_GET_SEARCH_MOVIES';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
export const REQUEST_CLEAR_SEARCH_MOVIES = 'REQUEST_CLEAR_SEARCH_MOVIES';
export const PULL_TO_REFRESH = 'PULL_TO_REFRESH';
